## Tensorflow For Beginners

    - Load a prebuilt dataset.
    - Build a neural network machine learning model that classifies images.
    - Train this neural network.
    - Evaluate the accuracy of the model.


In [1]:
# importing tensorflow
import tensorflow as tf
print("Tensorflow verson :", tf.__version__)

Tensorflow verson : 2.11.0


#### Loading The Dataset

In [4]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train /255.0, x_test / 255.0

11490434/11490434 [==============================] - 103s 9us/step


#### Building The ML model

In [5]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape = (28, 28)),
    tf.keras.layers.Dense(128, activation = "relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [6]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.17302892,  0.17040867,  0.13680719, -0.39075547, -0.00138113,
        -0.19099107,  0.9229238 ,  0.7547394 ,  0.24723352, -0.10589351]],
      dtype=float32)

In [7]:
# The tf.nn.softmax function converts these logits to probabilities for each class
tf.nn.softmax(predictions).numpy()

array([[0.06729709, 0.09487447, 0.09173951, 0.05413011, 0.07989912,
        0.06609908, 0.20135505, 0.17018488, 0.10245048, 0.07197022]],
      dtype=float32)

In [8]:
# Define a loss function for training using losses.SparseCategoricalCrossentropy

loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [9]:
loss_fn(y_train[:1], predictions).numpy()

2.7166004

In [10]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])


#### Training the Model

In [11]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 13s 5ms/step - loss: 0.2933 - accuracy: 0.9151
Epoch 2/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.1398 - accuracy: 0.9586
Epoch 3/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.1055 - accuracy: 0.9683
Epoch 4/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0867 - accuracy: 0.9729
Epoch 5/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0723 - accuracy: 0.9777


In [12]:
# Model Evaluation
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0736 - accuracy: 0.9781 - 1s/epoch - 5ms/step


[0.07357438653707504, 0.9781000018119812]

In [13]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])


In [14]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[6.3680062e-08, 2.5300578e-08, 1.4719060e-06, 1.4808678e-04,
        2.9426996e-11, 2.2233097e-07, 2.6359531e-11, 9.9983096e-01,
        3.5373089e-06, 1.5639031e-05],
       [2.9841674e-09, 3.2960674e-05, 9.9996638e-01, 6.5180092e-07,
        1.2724139e-19, 8.7250385e-09, 1.2169714e-09, 1.2278238e-14,
        5.6977600e-11, 3.2893085e-17],
       [1.4937335e-07, 9.9960226e-01, 5.4329706e-05, 7.4368645e-06,
        2.1323583e-06, 1.5783118e-06, 3.5474848e-06, 3.1367620e-04,
        1.4783161e-05, 6.5999416e-08],
       [9.9952102e-01, 1.9274795e-08, 1.7355154e-04, 2.3301450e-06,
        1.2345207e-05, 3.0308361e-06, 2.6305957e-04, 2.3073520e-05,
        9.6433688e-09, 1.5740275e-06],
       [9.2240378e-05, 1.3801349e-09, 2.6737272e-05, 1.7951531e-07,
        9.9500412e-01, 5.2655560e-07, 5.6607285e-05, 3.4894900e-05,
        5.9720055e-06, 4.7787144e-03]], dtype=float32)>