#### Tensors

In [1]:
# importing tensorflow
import tensorflow as tf

In [2]:
x = tf.constant([[1., 2., 3.],
           [4., 5., 6.]])
print(x.shape)
print(x.dtype)

(2, 3)
<dtype: 'float32'>


#### tf.tensor implements calculations

In [3]:
x + x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [4]:
5 + x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 6.,  7.,  8.],
       [ 9., 10., 11.]], dtype=float32)>

In [5]:
x @ tf.transpose(x)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

In [6]:
tf.concat([x, x, x], axis = 0)

<tf.Tensor: shape=(6, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [1., 2., 3.],
       [4., 5., 6.],
       [1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [7]:
tf.nn.softmax(x, axis = -1)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.09003057, 0.24472848, 0.66524094],
       [0.09003057, 0.24472848, 0.66524094]], dtype=float32)>

In [8]:
tf.reduce_sum(x)

<tf.Tensor: shape=(), dtype=float32, numpy=21.0>

In [9]:
tf.convert_to_tensor(1, 2, 3)

<tf.Tensor: shape=(), dtype=float64, numpy=1.0>

In [10]:
tf.reduce_sum([1, 2, 3])

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [11]:
# Example 1
a = tf.constant(2)
b = tf.constant(3)
max_a_b = tf.maximum(a, b)
print(max_a_b) # Output: tf.Tensor(3, shape=(), dtype=int32)

tf.Tensor(3, shape=(), dtype=int32)


In [12]:
a = tf.constant(9)
b = tf.constant(7)

max = tf.maximum(a, b)
min = tf.minimum(a, b)

print("max ",max)
print("min ", min)

max  tf.Tensor(9, shape=(), dtype=int32)
min  tf.Tensor(7, shape=(), dtype=int32)


### More About Tensors

##### About Shapes

In [13]:
rank_4_tensor = tf.zeros([2, 1, 4])
print("Type of every element:", rank_4_tensor.dtype)
print("Number of axes:", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along the last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (3*2*4*5): ", tf.size(rank_4_tensor).numpy())


Type of every element: <dtype: 'float32'>
Number of axes: 3
Shape of tensor: (2, 1, 4)
Elements along axis 0 of tensor: 2
Elements along the last axis of tensor: 4
Total number of elements (3*2*4*5):  8


##### Indexing

In [14]:
rank_1_tensor = tf.constant([1,4,6,7,3,8,10,11,13,16,16,17,21,24])
print(rank_1_tensor)
print(rank_1_tensor.numpy())

tf.Tensor([ 1  4  6  7  3  8 10 11 13 16 16 17 21 24], shape=(14,), dtype=int32)
[ 1  4  6  7  3  8 10 11 13 16 16 17 21 24]


In [15]:
print("First:", rank_1_tensor[0].numpy())
print("Second:", rank_1_tensor[1].numpy())
print("Last:", rank_1_tensor[-1].numpy())

First: 1
Second: 4
Last: 24


In [16]:
print("Everything:", rank_1_tensor[:].numpy())
print("Before 4:", rank_1_tensor[:4].numpy())
print("From 4 to the end:", rank_1_tensor[4:].numpy())
print("From 2, before 7:", rank_1_tensor[2:7].numpy())
print("Every other item:", rank_1_tensor[::2].numpy())
print("Reversed:", rank_1_tensor[::-1].numpy())

Everything: [ 1  4  6  7  3  8 10 11 13 16 16 17 21 24]
Before 4: [1 4 6 7]
From 4 to the end: [ 3  8 10 11 13 16 16 17 21 24]
From 2, before 7: [ 6  7  3  8 10]
Every other item: [ 1  6  3 10 13 16 21]
Reversed: [24 21 17 16 16 13 11 10  8  3  7  6  4  1]


##### Maniplating Shapes

In [17]:
# Shape returns a `TensorShape` object that shows the size along each axis
x = tf.constant([[1], [2], [3]])
print(x.shape)

(3, 1)


In [18]:
# You can convert this object into a Python list, too
print(x.shape.as_list())

[3, 1]


In [19]:
# You can reshape a tensor to a new shape.
# Note that you're passing in a list
reshaped = tf.reshape(x, [1, 3])

In [20]:
print(x.shape)
print(reshaped.shape)

(3, 1)
(1, 3)


In [21]:
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [22]:
# A `-1` passed in the `shape` argument says "Whatever fits".

print(tf.reshape(rank_3_tensor, [-1]))

tf.Tensor(
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29], shape=(30,), dtype=int32)


In [23]:
print(tf.reshape(rank_3_tensor, [3*2, 5]))

tf.Tensor(
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]], shape=(6, 5), dtype=int32)


In [24]:
print(tf.reshape(rank_3_tensor, [3, -1]))

tf.Tensor(
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]], shape=(3, 10), dtype=int32)


### More of DTypes

In [25]:
the_f64_tensor = tf.constant([2.2, 3.3, 4.4], dtype = tf.float64)
the_f16_tensor = tf.constant([2.2, 3.3, 4.4], dtype = tf.float16)

# Now, cast to an uint8 and lose the decimal precision
the_u8_tensor = tf.cast(the_f16_tensor, dtype = tf.uint8)

In [26]:
the_u8_tensor

<tf.Tensor: shape=(3,), dtype=uint8, numpy=array([2, 3, 4], dtype=uint8)>

In [27]:
the_f64_tensor

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2.2, 3.3, 4.4])>

In [28]:
the_f16_tensor

<tf.Tensor: shape=(3,), dtype=float16, numpy=array([2.2, 3.3, 4.4], dtype=float16)>

### BroadCasting

In [31]:
x = tf.constant([1, 3, 5])
y = tf.constant(2)
z = tf.constant([2, 2, 2])

# All of these are same Computations
print(tf.multiply(x, 2))
print(x * y)
print(y * z)

tf.Tensor([ 2  6 10], shape=(3,), dtype=int32)
tf.Tensor([ 2  6 10], shape=(3,), dtype=int32)
tf.Tensor([4 4 4], shape=(3,), dtype=int32)


In [32]:
# These are the same computations
x = tf.reshape(x,[3,1])
y = tf.range(1, 5)
print(x, "\n")
print(y, "\n")
print(tf.multiply(x, y))

tf.Tensor(
[[1]
 [3]
 [5]], shape=(3, 1), dtype=int32) 

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32) 

tf.Tensor(
[[ 1  2  3  4]
 [ 3  6  9 12]
 [ 5 10 15 20]], shape=(3, 4), dtype=int32)


In [33]:
x_stretch = tf.constant([[1, 1, 1, 1],
                         [2, 2, 2, 2],
                         [3, 3, 3, 3]])

y_stretch = tf.constant([[1, 2, 3, 4],
                         [1, 2, 3, 4],
                         [1, 2, 3, 4]])

print(x_stretch * y_stretch)  # Again, operator overloading


tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)


### tf.convert to tensor

- Most ops, like tf.matmul and tf.reshape take arguments of class tf.Tensor. However, you'll notice in the above case, Python objects shaped like tensors are accepted.

- Most, but not all, ops call convert_to_tensor on non-tensor arguments. There is a registry of conversions, and most object classes like NumPy's ndarray, TensorShape, Python lists, and tf.Variable will all convert automatically.

- See tf.register_tensor_conversion_function for more details, and if you have your own type you'd like to automatically convert to a tensor.